# General Information
title: Bishop Tracker
author: Bishop Tracker
email: bishoptracker2018@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bishop Tracker visualizes location data for on crimes of sexual abuse by Catholic Bishops throughout the world for awareness, empowerment, and action. More data is being added everyday so please check back.
# Build settings
url: bishoptracker.com
permalink: pretty
# SASS directory
sass:
    sass_dir: _sass
# Custom pages directory to keep root directory uncluttered
include: ['_pages']
# Markdown
markdown: kramdown
# GitHub flavored Markdown
input: GFM
# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-maps
maps:
  google:
    api_key: AIzaSyAoMGz9AeBlBnEzge5UUikE2BpBvfJj6c4
